### ISSUE TITLE
dead links on API reference

### ISSUE THREAD

**Issue by ThijsMaasLaw** [onramper/docs#3]
there's a dead links on the API reference (I don't know what the correct URL is to link to so I'll just mention it here):

https://github.com/onramper/docs/blob/dev/docs/API-Reference.md
dead link:
https://github.com/onramper/widget/tree/dev/src/OnramperWidget/ApiContext/api/types%22

**Comment by corollari** [comment]
Btw you can directly use https://docs.onramper.dev

**Comment by salahzsh** [comment]
Right, fixed👌
